{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func():\n    \n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "ddd4eb86-5482-4398-a4ce-f5ec087750b6-attachment.txt", "type": "text/plain"}], "start": 1670309719413, "stop": 1670309719414, "uuid": "02276a87-c3c7-485a-9a76-3ae4002b9577", "historyId": "bf70add9cd936f57dc4aaa1d7af3cdce", "testCaseId": "22bd134fd6b6beae68c2bbbf5dd34e38", "fullName": "Testcase_Api.test_login#test_func", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "14524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}