{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func1():\n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1==2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:26: AssertionError"}, "attachments": [{"name": "log", "source": "6690cb91-ead2-4138-87b5-c88d596395c4-attachment.txt", "type": "text/plain"}], "start": 1670309719538, "stop": 1670309719539, "uuid": "6ec1faf1-de67-45d7-bfc0-269976aa3d57", "historyId": "ee71ebfd0726d4c3ac85001f80e8606c", "testCaseId": "4db44947c34045a865f5c8d68c351cac", "fullName": "Testcase_Api.test_login#test_func1", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "14524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}