{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func():\n    \n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "ea1c5233-f5e6-4326-890e-8c4b375ee35f-attachment.txt", "type": "text/plain"}], "start": 1670309693430, "stop": 1670309693431, "uuid": "c26daec1-cc88-4f85-84f2-054805284da1", "historyId": "bf70add9cd936f57dc4aaa1d7af3cdce", "testCaseId": "22bd134fd6b6beae68c2bbbf5dd34e38", "fullName": "Testcase_Api.test_login#test_func", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "14472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}