{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func1():\n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1==2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:26: AssertionError"}, "attachments": [{"name": "log", "source": "bf8c96bc-8832-4b8b-bf66-9f7dde3d1136-attachment.txt", "type": "text/plain"}], "start": 1670308396621, "stop": 1670308396622, "uuid": "96d8d961-eba0-4311-b655-3060d855f9d4", "historyId": "ee71ebfd0726d4c3ac85001f80e8606c", "testCaseId": "4db44947c34045a865f5c8d68c351cac", "fullName": "Testcase_Api.test_login#test_func1", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "5708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}