{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func():\n    \n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "3610b9fb-798d-4d57-a6b5-ca2cfcf3cffe-attachment.txt", "type": "text/plain"}], "start": 1670308454383, "stop": 1670308454383, "uuid": "5d5a358a-fe74-4639-95f8-15ee53aa4e2d", "historyId": "bf70add9cd936f57dc4aaa1d7af3cdce", "testCaseId": "22bd134fd6b6beae68c2bbbf5dd34e38", "fullName": "Testcase_Api.test_login#test_func", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "14352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}