{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"11\")\n    def test_func():\n    \n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "d021a9b8-b483-4a8e-922a-e87647c9e050-attachment.txt", "type": "text/plain"}], "start": 1670308330472, "stop": 1670308330473, "uuid": "e29c3a5c-534a-493d-8203-4e5d744a30d4", "historyId": "bf70add9cd936f57dc4aaa1d7af3cdce", "testCaseId": "22bd134fd6b6beae68c2bbbf5dd34e38", "fullName": "Testcase_Api.test_login#test_func", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "2284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}